### ISSUE TITLE
[Request] Add Login and User managment

### ISSUE THREAD

**Issue by timowevel03** [TayebBou/E-Learning-Courses#1]
Hey!

First, thank you for this amazing app. I really like it.

Do you plan to add the possibility to add courses, assign users to it, allow users to login and see their individual courses then?

Thanks!

**Comment by TayebBou** [comment]
I'm not sure about adding all these features it will took a lot of time, I'm sorry. It's just a simple application where I'm sharing how to integrate jitsi in your react app and some stuff but for adding authentification I need to use redux and to create a backend for users and courses also secure the authentification with JWT and do the API and pages in react It's a big work. And Unfortunately I don't have a lot of free time. 

Here is my email if you want to contact me : TAYEBBOUSFIHA72@GMAIL.COM
